### ISSUE TITLE
Install as Winget package

### ISSUE THREAD

**Issue by MadSpindel** [PolarGoose/CoffeeBean#1]
Maybe publish this to Winget (https://github.com/microsoft/winget-pkgs) and make it possible to do something like

```
winget install coffeebean
coffebean start
coffebean stop
```

**Comment by PolarGoose** [comment]
@MadSpindel,

Thank you for the proposal.
> Maybe publish this to Winget

It is a good idea, indeed. I will think about it.

> coffebean start
> coffebean stop

You can easily achieve the same by:
```
CoffeeBean.exe
Taskkill /F /IM CoffeeBean.exe
```

**Comment by PolarGoose** [comment]
@MadSpindel,

I have updated the application, now you can do:
```
CoffeeBean.exe enable
CoffeeBean.exe disable
```

**Comment by PolarGoose** [comment]
Winget package is also on its way:
https://github.com/microsoft/winget-pkgs/pull/39616#issuecomment-1003616480

I'm closing this ticket.
