### ISSUE TITLE
I'm an idiot

### ISSUE THREAD

**Issue by yancypants** [PolarGoose/CoffeeBean#2]
Is there a way to just download and run this, or do I need to know stuff? App sounds great, but I don't know anything about building anything.

**Comment by PolarGoose** [comment]
@yancypants,

Sorry for the unclear instruction in the Readme.
You don't need to build anything. Just download the latest release archive:
https://github.com/PolarGoose/CoffeeBean/releases/latest/download/CoffeeBean.zip
Unpack it and run.
For more details look at:
https://github.com/PolarGoose/CoffeeBean#how-to-use

Let me know if you need more details.

**Comment by yancypants** [comment]
I downloaded and unpacked the zip file, but I'm not sure which file is the executable. Didn't see anything obvious like *.exe (or at least not obvious to me).

**Comment by PolarGoose** [comment]
@yancypants,

the `CoffeeBean.zip` archive contains only one file: `CoffeeBean.exe` this is the executable which you need to run.

**Comment by yancypants** [comment]
Ah, now I see the link on the side under releases. Before I just clicked the big green button with the download arrow, which was source code. Confirmed idiot. ;-) Thanks again!
