### ISSUE TITLE
[FREQ] Pause functionality

### ISSUE THREAD

**Issue by rbukovansky** [PolarGoose/CoffeeBean#3]
Hi,
I like your application, but would it be possible to add the "Pause/Unpause" function so I don't need to quit CoffeeBean and start it again when needed? This function could be called from the systray icon menu and/or by a configurable global keyboard shortcut.

Thank you.

Richard Bukovansky

**Comment by PolarGoose** [comment]
@rbukovansky ,
Thank you for the feature request.

I have updated the application. Now you can enable or disable screen locking from the context menu. You can also control screen locking behavior from console and therefore if you want to have a hotkey you can easily use something like Autohotkey to script this behavior

**Comment by rbukovansky** [comment]
@PolarGoose This is just awesome! Thank you!
