### ISSUE TITLE
Please make this work for remote desktop sessions (nt)

### ISSUE THREAD

**Issue by fs30000** [PolarGoose/CoffeeBean#4]

**Comment by PolarGoose** [comment]
Could you please provide more details?

**Comment by fs30000** [comment]
This only works if installed locally, right? How about for remote desktop sessions?

**Comment by PolarGoose** [comment]
> How about for remote desktop sessions?

You can drop the executable into your remote session and run it there. Then your remote session will also not go to screen-lock

**Comment by fs30000** [comment]
Yes, that's what i did. I was avoiding running it inside the remote pc. Works great :) thanks for it!
Feel free to delete this issue.

**Comment by PolarGoose** [comment]
The issues is closed
