### ISSUE TITLE
Feature request: auto-pause when computer is locked

### ISSUE THREAD

**Issue by pdolezal** [PolarGoose/CoffeeBean#5]
Hello, thanks for this great application. Works perfectly, perhaps too much 😉 I would quite like let the screensaver do its job (in my case simply make the screen black in order not to shine uselessly) when I lock the computer.

Would it be possible to add a check menu item that would auto-pause when the computer is locked?

**Comment by PolarGoose** [comment]
Hello @pdolezal ,

Thank you for the bug report.
Indeed, It is something that needs to be fixed. It seems it is possible to implement.
I have found several solutions that I need to try.

**Comment by pdolezal** [comment]
Great 😄👍 I'm looking forward to the update.

**Comment by PolarGoose** [comment]
@pdolezal ,
I have implemented the required changes. Could you please test that they work for you?

**Comment by pdolezal** [comment]
@PolarGoose Hi, I had not many occasions to test it, but so far it seems working – the lock screen gets blank after the configured timeout. I think the issue can be closed. If I observe any problems, I'll reopen it/file a new issue and let you know. Anyway, thanks 👍

**Comment by PolarGoose** [comment]
@pdolezal,
Thank you for testing. I have also checked that it works.
I'm closing this issue.
